services:
  poetry-armv7:
    image: nanomad/poetry:2.1.3-python-3.12
    build:
      context: .
    platform: linux/arm/v7
    restart: no
    command:
      - poetry --version
  poetry-arm64v8:
    image: nanomad/poetry:2.1.3-python-3.12
    build:
      context: .
    platform: linux/arm64/v8
    restart: no
    command:
      - poetry --version
  poetry-amd64:
    image: nanomad/poetry:2.1.3-python-3.12
    build:
      context: .
    platform: linux/amd64
    restart: no
    command:
      - poetry --version
